### ISSUE TITLE
Application state seems to update only on triggering a consecutive mutation.

### ISSUE THREAD

**Issue by Eraldo** [kamilkisiela/apollo-angular-link-network-status#1]
Since I added this package to my project, I need to send a mutation twice to update the apollo cache to show the right result. 

I don't yet understand why that is the case.

Changing from:
```
 link: networkStatus.concat(
   httpLink.create({uri: uri, withCredentials: true})
 ),
```
to:
```
link: httpLink.create({uri: uri, withCredentials: true}),
```
Removed the bug for me.

You can confirm this issue by pressing the vote button in the demo: https://stackblitz.com/edit/apollo-angular-network-status

**Comment by Eraldo** [comment]
Any ideas on how to fix it?

**Comment by kamilkisiela** [comment]
@Eraldo I don't understand the issue, is mutation triggered twice? Could you create a reproduction?

ABout the demo and the vote button. Two requests are fine, first one is `OPTIONS`, and second `POST` because of cors.

**Comment by Eraldo** [comment]
Oh I guess I did not describe it clear enough.

1. Open this demo:  https://stackblitz.com/edit/apollo-angular-network-status
  + Expected: Seeing vote buttons with initial state.
  + Actual: Seeing vote buttons with initial state.

2. Click on the first vote button.
  + Expected: First vote counter goes up +1.
  + Actual: No change to vote counters.

3. Click on the first vote button again.
  + Expected: First vote counter goes up +1.
  + Actual: First vote now goes up by one. (expected from previous)

4. Click on the second vote button.
  + Expected: **Second** vote counter goes up +1.
  + Actual: **First** vote now goes up by one. (expected from previous)

So the way I see it there is always in delay in state.
On the next sent mutation I get the state reflected that I expect from the previous mutation.

@kamilkisiela Does that help reproduce the issue?

PS: Thank you for looking into this. :)

**Comment by Eraldo** [comment]
Any updates?

**Comment by kamilkisiela** [comment]
v1.0.4 fixes it
