### ISSUE TITLE
compatibility with angular 7x

### ISSUE THREAD

**Issue by Eraldo** [kamilkisiela/apollo-angular-link-network-status#2]
When I try to update my project to the latest stable versions of dependencies.
I get a warning that `apollo-angular-link-network-status` requires angular 6.
```
Package "apollo-angular-link-network-status" has an incompatible peer dependency to "@angular/core" (requires "^6.0.0 | ^7.0.0", would install "7.2.12").
```

Workaround:
1. Remove `apollo-angular-link-network-status`
2. Update as desired
3. Add `apollo-angular-link-network-status` again.

It seems to me that `apollo-angular-link-network-status` is compatible with angular 7 but that is not reflected in the dependencies.

Keeping it pinned to the latest confirmed working state is a smart move, so I totally get why this is the case since you have many things to take care of. ^^

I would like to know if there are currently any reasons for keeping it at v6 that I am not aware of or if it might be time to update the pinned dependencies. :)

**Comment by kamilkisiela** [comment]
`v1.0.4` should fix it
